---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ts-next-template.fullname" . }}-secret
  labels:
    {{- include "ts-next-template.labels" . | nindent 4 }}
type: Opaque
data:
  # database-url should be provided during helm install via --set
  database-url: {{ .Values.database.url | b64enc | quote }}
