---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ts-next-template.fullname" . }}-oauth
  labels:
    {{- include "ts-next-template.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.oauthService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ts-next-template.selectorLabels" . | nindent 4 }}
    app: oauth-service

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ts-next-template.fullname" . }}-admin
  labels:
    {{- include "ts-next-template.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.adminPortal.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ts-next-template.selectorLabels" . | nindent 4 }}
    app: admin-portal
