[package]
name = "oauth-models"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true }
serde_json.workspace = true
sqlx = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
